Register page
PhupaSirirat/SE-TermProject pull request #5
Opened 2023-11-08 08:10 UTC by KanbH

-Added a Register page.
-Created the Register page.
-Integrated the Register page into the router.
-Made changes to the InputForm component.

2023-11-08 17:36 UTC, PhupaSirirat requested changes
Dont forget to 'git merge main'. And resolve conflic.

2023-11-09 03:39 UTC, KanbH commented
Conflict resolved

2023-11-09 11:56 UTC, PhupaSirirat requested changes
Sorry, forgot to submit review. lol

2023-11-09 11:56 UTC, PhupaSirirat commented on src/Register.jsx
> +          <InputForm label="ยืนยันรหัสผ่าน" type="confirmpassword" id="confirmpassword" />
This type of InputFrom should be 'password'.
```suggestion
          <InputForm label="ยืนยันรหัสผ่าน" type="password" id="confirmpassword" />
```

2023-11-09 11:56 UTC, PhupaSirirat commented on src/components/InputForm.jsx
> +        </label>
We already have label at the top of this code.

2023-11-10 09:52 UTC, PhupaSirirat approved these changes

2023-11-10 09:52 UTC, merged